export const APP_LOADING = "APP_LOADING"
export const APP_LOADING_SUCCESS = "APP_LOADING_SUCCESS"
export const APP_LOADING_FAILURE = "APP_LOADING_FAILURE"

export const APP_DATA_LOADING = "APP_DATA_LOADING"
export const APP_DATA_LOADING_SUCCESS = "APP_DATA_LOADING_SUCCESS"
export const APP_DATA_LOADING_FAILURE = "APP_DATA_LOADING_FAILURE"

export const APP_DATA_DETAIL_LOADING = "APP_DATA_DETAIL_LOADING" 
export const APP_DATA_DETAIL_SUCCESS = "APP_DATA_DETAIL_SUCCESS" 
export const APP_DATA_DETAIL_FAILURE = "APP_DATA_DETAIL_FAILURE" 

export const APP_GOTO_HOME = "APP_GOTO_HOME"; 
export const APP_GOTO_DETAIL = "APP_GOTO_DETAIL"; 